name: Build n Release Synology Smart Info Package

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-spk:
    name: Build Package (kvmx64, 7.2)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Package
        uses: tomgrv/synology-package-builder@v1.3.0
        with:
          dsm: "7.2"
          arch: "kvmx64"
          output: "./dist"

      - name: Upload Package
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            ./dist/*.spk
